interface Example {
    lang: string;
    text: string;
}

export const ITALIAN_EXAMPLE: Example = {
    lang: 'it',
    text: `Il supercomputer (o superelaboratore) è un tipo di sistema di elaborazione progettato per ottenere capacità di elaborazione estremamente elevate, dedicato ad eseguire calcoli matematici ad elevate prestazioni.

    Usualmente si ritiene che i supercomputer siano i più potenti computer del pianeta, questa classificazione comprende tutti i primi computer a partire dalla macchina analitica di Babbage passando per i vari modelli di Zuse (i primi computer funzionanti) fino ad arrivare ai supercomputer dei giorni nostri.
    
    Molti esperti dell'informatica invece fanno risalire i supercomputer agli anni cinquanta e in particolare al NORC prodotto da IBM per via delle soluzioni particolari adottate per ottenere una macchina con le migliori prestazioni e quindi con soluzioni tecniche diverse da quelle utilizzate per i modelli precedenti.
    
    Il termine super computing venne utilizzato per la prima volta dal quotidiano New York World nel 1920 in un articolo che descriveva una macchina elettromeccanica costruita dall'IBM per la Columbia University
    
    Tra gli anni sessanta e la metà degli anni settanta la società CDC con i suoi supercomputer fu l'azienda leader del settore. I tecnici della CDC per ottenere elevate prestazioni di calcolo svilupparono diverse soluzioni tecnologiche come l'utilizzo di processori specializzati per i diversi compiti (CDC 6600) l'utilizzo di pipeline (CDC 7600) e l'utilizzo di processori vettoriali (CDC STAR-100). Scelte strategiche della CDC rischiarono di far fallire la società e alcuni tecnici insoddisfatti dei dirigenti della società abbandonarono la CDC per tentare nuove strade. Tra questi il più famoso fu Seymour Cray che con il Cray-1 segnò una nuova strada per le soluzioni tecnologiche utilizzate e per l'elevata potenza di calcolo sviluppata.
    
    Dalla metà degli anni settanta fino alla fine degli anni ottanta la Cray Research rappresentò il leader nel settore del supercalcolo. Cray estese le innovazioni utilizzate nelle macchine della CDC portandole al loro estremo ed utilizzando soluzioni innovative come il raffreddamento a liquido o delle strutture a torre ove alloggiare le schede con le unità di calcolo in modo da ridurre la lunghezza media delle connessioni.
    
    Durante gli anni 80 si assistette alla nascita di molte società che svilupparono sistemi di calcolo ad alte prestazioni. Queste piccole società entrarono in concorrenza con realtà affermate come IBM o Cray e le costrinsero a effettuare radicali riduzioni di prezzo dei sistemi per rimanere competitive. Alla fine degli anni 80 e anni novanta i supercomputer divennero macchine a parallelismo massivo basate su centinaia se non migliaia di processori elementari. Inizialmente questi processori erano ancora dei processori sviluppati esplicitamente per il supercalcolo come quelli utilizzati dal CM-5/1024 ma verso la fine degli anni novanta oramai si era passati definitivamente a processori generici che fornivano elevate prestazioni e costi ridotti per via della produzione in serie attuata da ditte come Intel o AMD. Le piccole ditte nate durante gli anni 80 erano fallite o erano state assorbite dalle grosse società, la stessa Cray fallì e fu acquisita dalla Silicon Graphics.
    
    Negli ultimi anni i supercomputer sono macchine sempre più parallele e dotate di un numero sempre maggiore di processori elementari. Esempio eclatante fu il Blue Gene/L che con i suoi 212 992 processori divenne la macchina più potente del pianeta quando fu presentato. Lo sviluppo di questi sistemi oramai è svolto da grandi società di informatica come IBM o HP per via degli elevati costi di realizzazione dei sistemi di calcolo. I supercomputer oramai sono macchine costruite su ordinazione, sono pezzi unici progettati per le specifiche necessità dell'acquirente e realizzati assemblando componenti standard in modo da contenere i costi di sviluppo e produzione.
    
    È da notare che l'Europa dopo un inizio promettente non ha mai trainato la ricerca dell'ambito dei supercomputer e in generale dei computer. Dalla seconda guerra mondiale fino agli anni 90 gli Stati Uniti d'America hanno praticamente posseduto sempre i più potenti computer del pianeta. Ma dagli anni 90 in poi il Giappone ha iniziato ad imporsi come concorrente credibile all'egemonia statunitense grazie a cospicui finanziamenti pubblici a progetti di supercalcolo svolti da società nipponiche in cooperazioni con le locali università, particolarmente significativo è stato lo sforzo di NEC nel settore. Negli anni 2000 il progetto Blue Gene (finanziato dal Dipartimento della Difesa Statunitense) ha rinsaldato la posizione statunitense, ma negli ultimi anni progetti cinesi e giapponesi sembrano poter rimettere in discussione la leadership statunitense.
       
    Ciò che differenzia un supercomputer da un classico computer non è solo la maggior potenza di calcolo ma anche le architetture utilizzate per sviluppare queste macchine. I classici computer sono progettati secondo l'architettura di von Neumann, dato che le operazioni che l'utente esegue di solito con la macchina possono essere svolte in modo efficiente da questa architettura. I supercomputer invece spesso analizzano molti dati senza una vera interazione dell'utente, dato che usualmente devono eseguire un numero ridotto di operazioni su un elevato numero di dati. I supercomputer, quindi, utilizzano architetture alternative che sono in grado di assolvere questi compiti con maggiore efficienza rispetto all'architettura di Von Neumann.
    
    Negli ultimi anni questa distinzione si è comunque affievolita, dato che il diffondersi dei giochi tridimensionali ha costretto i computer classici e le loro schede grafiche ad adottare soluzioni sviluppate per i supercomputer, consentendo di ottenere elevate prestazioni a prezzi modesti, poiché i componenti sono venduti in decine (o centinaia) di milioni di pezzi e, quindi, i costi di ricerca e sviluppo sono distribuiti su un numero di elementi molto ampio.
    
    Contestualmente l'aumento della potenza di calcolo dei microprocessori per computer, e problemi di carattere tecnico legati alla difficoltà di elevare le frequenze di funzionamento delle CPU, hanno spinto il settore del supercalcolo verso l'utilizzo di soluzioni classiche in modo da abbattere i costi senza penalizzare le prestazioni. Infatti i supercomputer più potenti del pianeta utilizzano microprocessori standard in collaborazioni con schede grafiche. I processori grafici delle schede grafiche si sono rivelati essere molto prestanti per alcune tipologie di operazioni matematiche comuni sulle elaborazioni scientifiche, quindi i moderni supercomputer utilizzano batterie di schede grafiche ad alte prestazioni.
    
    I supercomputer sono ovviamente strumenti costosi, normalmente di proprietà di società o enti di ricerca che condividono il loro utilizzo tra molti dipendenti/ricercatori. Vista la velocità attuale dello sviluppo tecnologico nel campo dell'informatica e dei microprocessori, di solito perdono l'aggettivo "super" dopo pochi anni dalla loro nascita, superati da macchine ancora più potenti.
    
    In passato, i supercomputer erano dotati di architetture più sofisticate e componentistica migliore degli usuali computer al fine di poter svolgere con maggior efficienza le elaborazioni assegnate. Tuttavia, a partire dagli anni novanta, il divario fra la potenza delle CPU per supercomputer e i normali microprocessori commerciali è andato assottigliandosi progressivamente, e l'architettura dei supercomputer ha visto crescere progressivamente il numero di CPU impiegate. Attualmente la maggior parte dei nuovi supercomputer in progetto e di quelli in funzione sono basati su cluster di migliaia o addirittura centinaia di migliaia di unità di calcolo non molto più potenti di un buon personal computer, connesse da reti locali ad alta velocità e coordinate da estensioni apposite del sistema operativo adottato, generalmente una versione di Unix: una di queste estensioni, openMosix, è anche open source.
    
    Un parallelismo di calcolo simile è sfruttato da qualche anno a questa parte anche nei computer commerciali con le cosiddette tecnologie multicore.
    
    Il parallelismo sempre più massiccio dei supercomputer e in generale delle macchine nate per garantire elevate capacità di calcolo ha stimolato molte ricerche in campo software per esplicitare il parallelismo intrinseco nelle operazioni e nei programmi: queste ricerche hanno portato alla definizione di alcuni linguaggi di programmazione paralleli, come l'Occam, che è senz'altro il più diffuso del gruppo.[senza fonte]
    `,
};

export const ENGLISH_EXAMPLE: Example = {
    lang: 'en',
    text: `A supercomputer is a computer with a high level of performance as compared to a general-purpose computer. The performance of a supercomputer is commonly measured in floating-point operations per second (FLOPS) instead of million instructions per second (MIPS). Since 2017, there are supercomputers which can perform over 1017 FLOPS (a hundred quadrillion FLOPS, 100 petaFLOPS or 100 PFLOPS).[3]

    For comparison, a desktop computer has performance in the range of hundreds of gigaFLOPS to tens of teraFLOPS.[4][5]
    
    Since November 2017, all of the world's fastest 500 supercomputers run Linux-based operating systems.[6] Additional research is being conducted in the United States, the European Union, Taiwan, Japan, and China to build faster, more powerful and technologically superior exascale supercomputers.[7]
    
    Supercomputers play an important role in the field of computational science, and are used for a wide range of computationally intensive tasks in various fields, including quantum mechanics, weather forecasting, climate research, oil and gas exploration, molecular modeling (computing the structures and properties of chemical compounds, biological macromolecules, polymers, and crystals), and physical simulations (such as simulations of the early moments of the universe, airplane and spacecraft aerodynamics, the detonation of nuclear weapons, and nuclear fusion). They have been essential in the field of cryptanalysis.[8]
    
    Supercomputers were introduced in the 1960s, and for several decades the fastest were made by Seymour Cray at Control Data Corporation (CDC), Cray Research and subsequent companies bearing his name or monogram. The first such machines were highly tuned conventional designs that ran more quickly than their more general-purpose contemporaries. Through the decade, increasing amounts of parallelism were added, with one to four processors being typical. In the 1970s, vector processors operating on large arrays of data came to dominate. A notable example is the highly successful Cray-1 of 1976. Vector computers remained the dominant design into the 1990s. From then until today, massively parallel supercomputers with tens of thousands of off-the-shelf processors became the norm.[9][10]
    
    The US has long been the leader in the supercomputer field, first through Cray's almost uninterrupted dominance of the field, and later through a variety of technology companies. Japan made major strides in the field in the 1980s and 90s, with China becoming increasingly active in the field. As of June 2020, the fastest supercomputer on the TOP500 supercomputer list is Fugaku, in Japan, with a LINPACK benchmark score of 415 PFLOPS, followed by Summit, by around 266.7 PFLOPS.[11] The US has four of the top 10; China and Italy have two each, Switzerland has one.[11] In June 2018, all combined supercomputers on the TOP500 list broke the 1 exaFLOPS mark.[12]
    
    In 1960, UNIVAC built the Livermore Atomic Research Computer (LARC), today considered among the first supercomputers, for the US Navy Research and Development Center. It still used high-speed drum memory, rather than the newly emerging disk drive technology.[13] Also, among the first supercomputers was the IBM 7030 Stretch. The IBM 7030 was built by IBM for the Los Alamos National Laboratory, which in 1955 had requested a computer 100 times faster than any existing computer. The IBM 7030 used transistors, magnetic core memory, pipelined instructions, prefetched data through a memory controller and included pioneering random access disk drives. The IBM 7030 was completed in 1961 and despite not meeting the challenge of a hundredfold increase in performance, it was purchased by the Los Alamos National Laboratory. Customers in England and France also bought the computer, and it became the basis for the IBM 7950 Harvest, a supercomputer built for cryptanalysis.[14]
    
    The third pioneering supercomputer project in the early 1960s was the Atlas at the University of Manchester, built by a team led by Tom Kilburn. He designed the Atlas to have memory space for up to a million words of 48 bits, but because magnetic storage with such a capacity was unaffordable, the actual core memory of the Atlas was only 16,000 words, with a drum providing memory for a further 96,000 words. The Atlas operating system swapped data in the form of pages between the magnetic core and the drum. The Atlas operating system also introduced time-sharing to supercomputing, so that more than one program could be executed on the supercomputer at any one time.[15] Atlas was a joint venture between Ferranti and the Manchester University and was designed to operate at processing speeds approaching one microsecond per instruction, about one million instructions per second.[16]
    
    The CDC 6600, designed by Seymour Cray, was finished in 1964 and marked the transition from germanium to silicon transistors. Silicon transistors could run more quickly and the overheating problem was solved by introducing refrigeration to the supercomputer design.[17] Thus, the CDC6600 became the fastest computer in the world. Given that the 6600 outperformed all the other contemporary computers by about 10 times, it was dubbed a supercomputer and defined the supercomputing market, when one hundred computers were sold at $8 million each.[18][19][20][21]
    
    Cray left CDC in 1972 to form his own company, Cray Research.[19] Four years after leaving CDC, Cray delivered the 80 MHz Cray-1 in 1976, which became one of the most successful supercomputers in history.[22][23] The Cray-2 was released in 1985. It had eight central processing units (CPUs), liquid cooling and the electronics coolant liquid Fluorinert was pumped through the supercomputer architecture. It reached 1.9 gigaFLOPS, making it the first supercomputer to break the gigaflop barrier.[24]
       
    The only computer to seriously challenge the Cray-1's performance in the 1970s was the ILLIAC IV. This machine was the first realized example of a true massively parallel computer, in which many processors worked together to solve different parts of a single larger problem. In contrast with the vector systems, which were designed to run a single stream of data as quickly as possible, in this concept, the computer instead feeds separate parts of the data to entirely different processors and then recombines the results. The ILLIAC's design was finalized in 1966 with 256 processors and offer speed up to 1 GFLOPS, compared to the 1970s Cray-1's peak of 250 MFLOPS. However, development problems led to only 64 processors being built, and the system could never operate more quickly than about 200 MFLOPS while being much larger and more complex than the Cray. Another problem was that writing software for the system was difficult, and getting peak performance from it was a matter of serious effort.
    
    But the partial success of the ILLIAC IV was widely seen as pointing the way to the future of supercomputing. Cray argued against this, famously quipping that "If you were plowing a field, which would you rather use? Two strong oxen or 1024 chickens?"[25] But by the early 1980s, several teams were working on parallel designs with thousands of processors, notably the Connection Machine (CM) that developed from research at MIT. The CM-1 used as many as 65,536 simplified custom microprocessors connected together in a network to share data. Several updated versions followed; the CM-5 supercomputer is a massively parallel processing computer capable of many billions of arithmetic operations per second.[26]
    
    In 1982, Osaka University's LINKS-1 Computer Graphics System used a massively parallel processing architecture, with 514 microprocessors, including 257 Zilog Z8001 control processors and 257 iAPX 86/20 floating-point processors. It was mainly used for rendering realistic 3D computer graphics.[27] Fujitsu's VPP500 from 1992 is unusual since, to achieve higher speeds, its processors used GaAs, a material normally reserved for microwave applications due to its toxicity.[28] Fujitsu's Numerical Wind Tunnel supercomputer used 166 vector processors to gain the top spot in 1994 with a peak speed of 1.7 gigaFLOPS (GFLOPS) per processor.[29][30] The Hitachi SR2201 obtained a peak performance of 600 GFLOPS in 1996 by using 2048 processors connected via a fast three-dimensional crossbar network.[31][32][33] The Intel Paragon could have 1000 to 4000 Intel i860 processors in various configurations and was ranked the fastest in the world in 1993. The Paragon was a MIMD machine which connected processors via a high speed two-dimensional mesh, allowing processes to execute on separate nodes, communicating via the Message Passing Interface.[34]`,
};
